[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/storage",
    "crates/services",
    "crates/ui",
    "crates/app"
]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
