[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.7", features = ["asset", "desktop", "document"] }
dioxus-desktop = { version = "0.7" }
dioxus-router = { version = "0.7" }
